"""PyLage internal engine.

This package contains the framework runtime and implementation primitives.
It is intentionally not re-exported from the public ``pylage`` namespace.
"""

def run(*args, **kwargs):
    """Run a PyLage application using the server/browser runtime."""
    from pylage.ENGINE.app import run as _run
    return _run(*args, **kwargs)
from pylage.ENGINE.components import (
    Accordion,
    Alert,
    Audio,
    Avatar,
    Badge,
    Breadcrumbs,
    Button,
    Canvas,
    Card,
    Carousel,
    Checkbox,
    Column,
    DataFrame,
    DatePicker,
    Dialog,
    Divider,
    Drawer,
    Form,
    Grid,
    Heading,
    Icon,
    Image,
    Input,
    Label,
    Menu,
    Navigation,
    Option,
    Pagination,
    Popover,
    ProgressBar,
    RadioGroup,
    Row,
    Select,
    Skeleton,
    Slider,
    Spinner,
    Switch,
    Table,
    Tabs,
    Text,
    Toast,
    Tooltip,
    Video,
)
from pylage.ENGINE.core.reactive_list import ReactiveList
from pylage.ENGINE.core.state import State
from pylage.ENGINE.styling import ResponsiveStyle, Style, Theme

__all__ = [
    "Accordion",
    "Alert",
    "Audio",
    "Avatar",
    "Badge",
    "Breadcrumbs",
    "Button",
    "Canvas",
    "Card",
    "Carousel",
    "Checkbox",
    "Column",
    "DataFrame",
    "DatePicker",
    "Dialog",
    "Divider",
    "Drawer",
    "Form",
    "Grid",
    "Heading",
    "Icon",
    "Image",
    "Input",
    "Label",
    "Menu",
    "Navigation",
    "Option",
    "Pagination",
    "Popover",
    "ProgressBar",
    "RadioGroup",
    "ResponsiveStyle",
    "Row",
    "Select",
    "Skeleton",
    "Slider",
    "Spinner",
    "State",
    "Style",
    "Switch",
    "Table",
    "Tabs",
    "Text",
    "Theme",
    "Toast",
    "Tooltip",
    "Video",
    "run",
]
