[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "pylage"
version = "1.0.0"
description = "A server-driven differential UI framework for Python"
readme = "README.md"
requires-python = ">=3.10"
license = { file = "LICENSE" }
authors = [
  { name = "Rachit Kumar kanaujia", email = "kanaujia.rachit1991@gmail.com" }
]
keywords = ["ui", "framework", "server-driven", "differential-ui", "web"]
classifiers = [
    "Development Status :: 5 - Production/Stable",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: Apache Software License",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Topic :: Software Development :: User Interfaces",
    "Topic :: Internet :: WWW/HTTP :: Dynamic Content",
]
dependencies = [
    "websockets>=10.0"
]

[project.urls]
"Homepage" = "https://github.com/aanalyst-rachit/pylage"
"Bug Tracker" = "https://github.com/aanalyst-rachit/pylage/issues"

[tool.setuptools.packages.find]
where = ["."]
include = ["pylage*"]