"""Application examples and manual tests for PyLage UI."""

from . import (
    demo_accordion,
    demo_audio_video_canvas,
    demo_avatar_badge_divider,
    demo_button,
    demo_card,
    demo_carousel,
    demo_column,
    demo_data_feedback,
    demo_datepicker,
    demo_dialog,
    demo_drawer,
    demo_form,
    demo_grid,
    demo_heading,
    demo_input,
    demo_layout_primitives,
    demo_media,
    demo_menu_breadcrumbs_pagination,
    demo_modern_button,
    demo_nav_interaction,
    demo_pagination,
    demo_patterns,
    demo_popover_tooltip,
    demo_row,
    demo_select,
    demo_slider_radio_checkbox,
    demo_switch,
    demo_table,
    demo_tabs,
    demo_templates,
    demo_text,
    demo_themes_tokens,
    demo_overview,
)
